# Generated by Django 5.2.17 on 2026-09-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaVeterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota_id', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=200)),
                ('motivo', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=200)),
                ('tratamiento', models.CharField(max_length=200)),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=200)),
                ('raza', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.CharField(max_length=200)),
                ('peso', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('propietario_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=8)),
            ],
        ),
    ]
